// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Smart_Gadget

#include "../ui.h"

void ui_Clock_screen_init(void)
{
    ui_Clock = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Clock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Clock, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Clock, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Clock);
    lv_obj_set_width(ui_Panel1, 317);
    lv_obj_set_height(ui_Panel1, 237);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 1);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Clock);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -100);
    lv_obj_set_y(ui_Label1, -24);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Temperatura");

    ui_Humedad = lv_label_create(ui_Clock);
    lv_obj_set_width(ui_Humedad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humedad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humedad, -108);
    lv_obj_set_y(ui_Humedad, 6);
    lv_obj_set_align(ui_Humedad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Humedad, "Humedad");

    ui_Label2 = lv_label_create(ui_Clock);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -119);
    lv_obj_set_y(ui_Label2, 40);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Sonido");

    ui_Label3 = lv_label_create(ui_Clock);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -129);
    lv_obj_set_y(ui_Label3, 71);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Luz");

    ui_Button1 = lv_btn_create(ui_Clock);
    lv_obj_set_width(ui_Button1, 76);
    lv_obj_set_height(ui_Button1, 27);
    lv_obj_set_x(ui_Button1, -101);
    lv_obj_set_y(ui_Button1, -84);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x0B3E8E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button1, lv_color_hex(0xEEBFBF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Button1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Button1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Button1, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Inicio");

    ui_Button2 = lv_btn_create(ui_Clock);
    lv_obj_set_width(ui_Button2, 89);
    lv_obj_set_height(ui_Button2, 27);
    lv_obj_set_x(ui_Button2, -6);
    lv_obj_set_y(ui_Button2, -84);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x0B3E8E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button2, lv_color_hex(0xEEBFBF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Ventilador");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label5, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label5, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Clock);
    lv_obj_set_width(ui_Button3, 76);
    lv_obj_set_height(ui_Button3, 27);
    lv_obj_set_x(ui_Button3, 91);
    lv_obj_set_y(ui_Button3, -86);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x0B3E8E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button3, lv_color_hex(0xEEBFBF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Graficas");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label6, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_Label6, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ValorTemperatura = lv_label_create(ui_Clock);
    lv_obj_set_width(ui_ValorTemperatura, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValorTemperatura, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ValorTemperatura, 36);
    lv_obj_set_y(ui_ValorTemperatura, -22);
    lv_obj_set_align(ui_ValorTemperatura, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_ValorTemperatura, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_ValorTemperatura, "0");

    ui_ValorSonido = lv_label_create(ui_Clock);
    lv_obj_set_width(ui_ValorSonido, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValorSonido, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ValorSonido, 37);
    lv_obj_set_y(ui_ValorSonido, 40);
    lv_obj_set_align(ui_ValorSonido, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValorSonido, "0");

    ui_ValorLuz = lv_label_create(ui_Clock);
    lv_obj_set_width(ui_ValorLuz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValorLuz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ValorLuz, 36);
    lv_obj_set_y(ui_ValorLuz, 70);
    lv_obj_set_align(ui_ValorLuz, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValorLuz, "0");

    ui_ValorHumedad = lv_label_create(ui_Clock);
    lv_obj_set_width(ui_ValorHumedad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValorHumedad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ValorHumedad, 36);
    lv_obj_set_y(ui_ValorHumedad, 9);
    lv_obj_set_align(ui_ValorHumedad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValorHumedad, "0");

    ui_Label26 = lv_label_create(ui_Clock);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -129);
    lv_obj_set_y(ui_Label26, 102);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Gas");

    ui_ValorGas = lv_label_create(ui_Clock);
    lv_obj_set_width(ui_ValorGas, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ValorGas, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ValorGas, 36);
    lv_obj_set_y(ui_ValorGas, 101);
    lv_obj_set_align(ui_ValorGas, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ValorGas, "0");

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Clock, ui_event_Clock, LV_EVENT_ALL, NULL);

}
