// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Smart_Gadget

#include "../ui.h"

void ui_Splash_screen_init(void)
{
    ui_Splash = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Splash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Splash, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Splash, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Demo1 = lv_label_create(ui_Splash);
    lv_obj_set_width(ui_Demo1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Demo1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Demo1, 0);
    lv_obj_set_y(ui_Demo1, 75);
    lv_obj_set_align(ui_Demo1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Demo1, "V1.0");
    lv_obj_set_style_text_color(ui_Demo1, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Demo1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Demo1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AmbiSense = lv_label_create(ui_Splash);
    lv_obj_set_width(ui_AmbiSense, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AmbiSense, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AmbiSense, 0);
    lv_obj_set_y(ui_AmbiSense, 50);
    lv_obj_set_align(ui_AmbiSense, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AmbiSense, "AmbiSense");
    lv_obj_set_style_text_color(ui_AmbiSense, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AmbiSense, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AmbiSense, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_Splash);
    lv_img_set_src(ui_Image5, &ui_img_ventilador__1png_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 127
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 127
    lv_obj_set_x(ui_Image5, 2);
    lv_obj_set_y(ui_Image5, -37);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Chart1 = lv_chart_create(ui_Splash);
    lv_obj_set_width(ui_Chart1, 200);
    lv_obj_set_height(ui_Chart1, 100);
    lv_obj_set_x(ui_Chart1, 1008);
    lv_obj_set_y(ui_Chart1, 29);
    lv_obj_set_align(ui_Chart1, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_Chart1, LV_CHART_TYPE_LINE);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 2, true, 50);
    lv_chart_set_axis_tick(ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 2, true, 25);
    lv_chart_series_t * ui_Chart1_series_1 = lv_chart_add_series(ui_Chart1, lv_color_hex(0x808080),
                                                                 LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_Chart1_series_1_array[] = { 0, 10, 20, 40, 80, 80, 40, 20, 10, 0 };
    lv_chart_set_ext_y_array(ui_Chart1, ui_Chart1_series_1, ui_Chart1_series_1_array);

    lv_obj_add_event_cb(ui_Splash, ui_event_Splash, LV_EVENT_ALL, NULL);

}
