// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Smart_Gadget

#ifndef _SMART_GADGET_UI_H
#define _SMART_GADGET_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
void Up_Animation(lv_obj_t * TargetObject, int delay);
void hour_Animation(lv_obj_t * TargetObject, int delay);
void min_Animation(lv_obj_t * TargetObject, int delay);
void sec_Animation(lv_obj_t * TargetObject, int delay);
void scrolldot_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
void ui_event_Splash(lv_event_t * e);
extern lv_obj_t * ui_Splash;
extern lv_obj_t * ui_Demo1;
extern lv_obj_t * ui_AmbiSense;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Chart1;
// SCREEN: ui_Clock
void ui_Clock_screen_init(void);
void ui_event_Clock(lv_event_t * e);
extern lv_obj_t * ui_Clock;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Humedad;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label4;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label5;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_ValorTemperatura;
extern lv_obj_t * ui_ValorSonido;
extern lv_obj_t * ui_ValorLuz;
extern lv_obj_t * ui_ValorHumedad;
// SCREEN: ui_Call
void ui_Call_screen_init(void);
void ui_event_Call(lv_event_t * e);
extern lv_obj_t * ui_Call;
void ui_event_Switch1(lv_event_t * e);
extern lv_obj_t * ui_Switch1;
void ui_event_Switch2(lv_event_t * e);
extern lv_obj_t * ui_Switch2;
void ui_event_Switch3(lv_event_t * e);
extern lv_obj_t * ui_Switch3;
void ui_event_Switch4(lv_event_t * e);
extern lv_obj_t * ui_Switch4;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label7;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label8;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Bajo;
extern lv_obj_t * ui_Medio;
extern lv_obj_t * ui_Alto;
extern lv_obj_t * ui_Apagar;
// SCREEN: ui_panelTemperatura
void ui_panelTemperatura_screen_init(void);
void ui_event_panelTemperatura(lv_event_t * e);
extern lv_obj_t * ui_panelTemperatura;
extern lv_obj_t * ui_gfcTemperatura;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label10;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label11;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label12;
void ui_event_btnGraficaTemperatura(lv_event_t * e);
extern lv_obj_t * ui_btnGraficaTemperatura;
extern lv_obj_t * ui_Image4;
void ui_event_btnGraficaHumedad(lv_event_t * e);
extern lv_obj_t * ui_btnGraficaHumedad;
extern lv_obj_t * ui_Image1;
void ui_event_btnGraficaSonido(lv_event_t * e);
extern lv_obj_t * ui_btnGraficaSonido;
extern lv_obj_t * ui_Image2;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_btnGraficaLuz;
extern lv_obj_t * ui_Label13;
// SCREEN: ui_panelHumedad
void ui_panelHumedad_screen_init(void);
void ui_event_panelHumedad(lv_event_t * e);
extern lv_obj_t * ui_panelHumedad;
extern lv_obj_t * ui_gfcHumedad;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label14;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label15;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label16;
void ui_event_btnGraficaTemperatura1(lv_event_t * e);
extern lv_obj_t * ui_btnGraficaTemperatura1;
extern lv_obj_t * ui_Image3;
void ui_event_btnGraficaHumedad1(lv_event_t * e);
extern lv_obj_t * ui_btnGraficaHumedad1;
extern lv_obj_t * ui_Image6;
void ui_event_btnGraficaSonido1(lv_event_t * e);
extern lv_obj_t * ui_btnGraficaSonido1;
extern lv_obj_t * ui_Image7;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_btnGraficaLuz1;
extern lv_obj_t * ui_Label17;
// SCREEN: ui_panelSonido
void ui_panelSonido_screen_init(void);
void ui_event_panelSonido(lv_event_t * e);
extern lv_obj_t * ui_panelSonido;
extern lv_obj_t * ui_gfcSonido;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label18;
void ui_event_Button16(lv_event_t * e);
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label19;
void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label20;
void ui_event_btnGraficaTemperatura2(lv_event_t * e);
extern lv_obj_t * ui_btnGraficaTemperatura2;
extern lv_obj_t * ui_Image8;
void ui_event_btnGraficaHumedad2(lv_event_t * e);
extern lv_obj_t * ui_btnGraficaHumedad2;
extern lv_obj_t * ui_Image9;
void ui_event_btnGraficaSonido2(lv_event_t * e);
extern lv_obj_t * ui_btnGraficaSonido2;
extern lv_obj_t * ui_Image10;
void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_btnGraficaLuz2;
extern lv_obj_t * ui_Label21;
// SCREEN: ui_panelLuz
void ui_panelLuz_screen_init(void);
void ui_event_panelLuz(lv_event_t * e);
extern lv_obj_t * ui_panelLuz;
extern lv_obj_t * ui_gfcLuz;
void ui_event_Button19(lv_event_t * e);
extern lv_obj_t * ui_Button19;
extern lv_obj_t * ui_Label22;
void ui_event_Button20(lv_event_t * e);
extern lv_obj_t * ui_Button20;
extern lv_obj_t * ui_Label23;
void ui_event_Button21(lv_event_t * e);
extern lv_obj_t * ui_Button21;
extern lv_obj_t * ui_Label24;
void ui_event_btnGraficaTemperatura3(lv_event_t * e);
extern lv_obj_t * ui_btnGraficaTemperatura3;
extern lv_obj_t * ui_Image11;
void ui_event_btnGraficaHumedad3(lv_event_t * e);
extern lv_obj_t * ui_btnGraficaHumedad3;
extern lv_obj_t * ui_Image12;
void ui_event_btnGraficaSonido3(lv_event_t * e);
extern lv_obj_t * ui_btnGraficaSonido3;
extern lv_obj_t * ui_Image13;
void ui_event_Button22(lv_event_t * e);
extern lv_obj_t * ui_Button22;
extern lv_obj_t * ui_btnGraficaLuz3;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_ventilador__1png_png);    // assets\ventilador._1png.png
LV_IMG_DECLARE(ui_img_pattern_png);    // assets\pattern.png
LV_IMG_DECLARE(ui_img_2131096662);    // assets\temperature-free-icon-temperature-icon-free-11553469636smayyrvo21.png
LV_IMG_DECLARE(ui_img_728093_png);    // assets\728093.png
LV_IMG_DECLARE(ui_img_sound_png26_png);    // assets\sound_PNG26.png
LV_IMG_DECLARE(
    ui_img_1466347900);    // assets\png-transparent-lightbulb-icon-incandescent-light-bulb-computer-icons-idea-silhouette-light-black-and-white.png

LV_FONT_DECLARE(ui_font_Number);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
