// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Smart_Gadget

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void btnAlto(lv_event_t * e);
void btnMedio(lv_event_t * e);
void btnBajo(lv_event_t * e);
void btnApagar(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
